services:
  - type: web
    name: ia-module-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PROJECT_NAME
        value: "AI_Module"
      - key: API_V1_STR
        value: "/api/v1"
      - key: GOOGLE_API_KEY
        sync: false # Set in dashboard
      - key: CORS_ORIGINS
        value: "[]" # Update later
      - key: API_SECRET_KEY
        sync: false # Set in dashboard
